const API_BASE = "/api/v1";

export const ENDPOINTS = {
  AUTH: {
    LOGIN: `${API_BASE}/auth/login`,
    REGISTER_ORGANIZATION: `${API_BASE}/auth/register/organization`,
    REGISTER_VENDOR: `${API_BASE}/auth/register/vendor`,
    LOGOUT: `${API_BASE}/auth/logout`,
    FORGOT_PASSWORD: `${API_BASE}/auth/forgot-password`,
    RESET_PASSWORD: `${API_BASE}/auth/reset-password`,
    ME: `${API_BASE}/auth/me`,
    CHANGE_PASSWORD: `${API_BASE}/auth/change-password`,
  },
  WORK_ORDERS: {
    LIST: `${API_BASE}/work-orders`,
    CREATE: `${API_BASE}/work-orders`,
    FINANCE_PENDING: `${API_BASE}/work-orders/finance/pending-approval`,
    VENDOR_ASSIGNED: `${API_BASE}/work-orders/vendor/assigned`,
    MARKETPLACE_OPEN: `${API_BASE}/work-orders/marketplace/open`,
    DETAIL: (id: string) => `${API_BASE}/work-orders/${id}`,
    UPDATE: (id: string) => `${API_BASE}/work-orders/${id}`,
    DELETE: (id: string) => `${API_BASE}/work-orders/${id}`,
    ASSIGN: (id: string) => `${API_BASE}/work-orders/${id}/assign`,
    VENDOR_CANDIDATES: (id: string) => `${API_BASE}/work-orders/${id}/vendor-candidates`,
    TECHNICIAN_CANDIDATES: (id: string) => `${API_BASE}/work-orders/${id}/technician-candidates`,
    TRANSITION: (id: string) => `${API_BASE}/work-orders/${id}/transition`,
    VENDOR_ACCEPT: (id: string) => `${API_BASE}/work-orders/${id}/vendor/accept`,
    VENDOR_REJECT: (id: string) => `${API_BASE}/work-orders/${id}/vendor/reject`,
    INVOICE: (id: string) => `${API_BASE}/work-orders/${id}/invoice`,
    COMMENTS: (id: string) => `${API_BASE}/work-orders/${id}/comments`,
    ACTIVITY: (id: string) => `${API_BASE}/work-orders/${id}/activity`,
    APPROVE: (id: string) => `${API_BASE}/work-orders/${id}/approve`,
    ATTACHMENTS: (id: string) => `${API_BASE}/work-orders/${id}/attachments`,
    PARTS: (id: string) => `${API_BASE}/work-orders/${id}/parts`,
    TIME_LOG: (id: string) => `${API_BASE}/work-orders/${id}/time-logs`,
    COMPLETION_APPROVE: (id: string) => `${API_BASE}/work-orders/${id}/completion/approve`,
    COMPLETION_REJECT: (id: string) => `${API_BASE}/work-orders/${id}/completion/reject`,
    COMPLETION_REQUEST_INFORMATION: (id: string) =>
      `${API_BASE}/work-orders/${id}/completion/request-information`,
  },
  ASSETS: {
    LIST: `${API_BASE}/assets`,
    CREATE: `${API_BASE}/assets`,
    UPDATE: (assetTag: string) => `${API_BASE}/assets/${encodeURIComponent(assetTag)}`,
    DELETE: (assetTag: string) => `${API_BASE}/assets/${encodeURIComponent(assetTag)}`,
    HISTORY: (assetTag: string) => `${API_BASE}/assets/${encodeURIComponent(assetTag)}/history`,
    DOCUMENTS: (assetTag: string) => `${API_BASE}/assets/${encodeURIComponent(assetTag)}/documents`,
    QR: (assetTag: string) => `${API_BASE}/assets/${encodeURIComponent(assetTag)}/qr`,
  },
  LOCATIONS: {
    LIST: `${API_BASE}/locations`,
    CREATE: `${API_BASE}/locations`,
    DETAIL: (id: string) => `${API_BASE}/locations/${id}`,
    UPDATE: (id: string) => `${API_BASE}/locations/${id}`,
    DELETE: (id: string) => `${API_BASE}/locations/${id}`,
    CHILDREN: (id: string) => `${API_BASE}/locations/${id}/children`,
  },
  VENDORS: {
    LIST: `${API_BASE}/vendors`,
    CREATE: `${API_BASE}/vendors`,
    DETAIL: (id: string) => `${API_BASE}/vendors/${id}`,
    UPDATE: (id: string) => `${API_BASE}/vendors/${id}`,
    DELETE: (id: string) => `${API_BASE}/vendors/${id}`,
    PERFORMANCE: (id: string) => `${API_BASE}/vendors/${id}/performance`,
    INVOICES: (id: string) => `${API_BASE}/vendors/${id}/invoices`,
    CERTIFICATIONS: (id: string) => `${API_BASE}/vendors/${id}/certifications`,
  },
  ORGANIZATION_VENDORS: {
    LIST: `${API_BASE}/organizations/me/vendors`,
    DETAIL: (id: string) => `${API_BASE}/organizations/me/vendors/${id}`,
    PERFORMANCE: (id: string) => `${API_BASE}/organizations/me/vendors/${id}/performance`,
    STATUS: (id: string) => `${API_BASE}/organizations/me/vendors/${id}/status`,
  },
  VENDOR_APPLICATIONS: {
    CREATE: `${API_BASE}/vendor-applications`,
    MINE: `${API_BASE}/vendor-applications/mine`,
  },
  QUOTATIONS: { CREATE: `${API_BASE}/quotations`, MINE: `${API_BASE}/quotations/mine` },
  CONTRACT_AWARDS: { RENEW: (id: string) => `${API_BASE}/contract-awards/${id}/renew` },
  INVOICES: {
    LIST: `${API_BASE}/invoices`,
    REVIEW: (id: string) => `${API_BASE}/invoices/${id}/review`,
    MARK_PAID: (id: string) => `${API_BASE}/invoices/${id}/paid`,
    DISPUTE: (id: string) => `${API_BASE}/invoices/${id}/dispute`,
  },
  INVENTORY: {
    ITEMS: `${API_BASE}/inventory/items`,
    BALANCES: `${API_BASE}/inventory/balances`,
    OVERVIEW: `${API_BASE}/inventory/overview`,
    HISTORY: `${API_BASE}/inventory/history`,
    CATEGORIES: `${API_BASE}/inventory/categories`,
    LOCATIONS: `${API_BASE}/inventory/locations`,
    LIST: `${API_BASE}/inventory/items`,
    CREATE: `${API_BASE}/inventory/items`,
    RECEIVE: `${API_BASE}/inventory/transactions/receive`,
    RESERVE: `${API_BASE}/inventory/transactions/reserve`,
    RELEASE: `${API_BASE}/inventory/transactions/release`,
    ISSUE: `${API_BASE}/inventory/transactions/issue`,
    CONSUME: `${API_BASE}/inventory/transactions/consume`,
    ADJUST: `${API_BASE}/inventory/transactions/adjust`,
    TRANSFER: `${API_BASE}/inventory/transactions/transfer`,
    RETURN: `${API_BASE}/inventory/transactions/return`,
    PURCHASE_REQUESTS: `${API_BASE}/inventory/purchase-requests`,
  },
  PM: {
    LIST: `${API_BASE}/preventive-maintenance`,
    CREATE: `${API_BASE}/preventive-maintenance`,
    DETAIL: (id: string) => `${API_BASE}/preventive-maintenance/${id}`,
    UPDATE: (id: string) => `${API_BASE}/preventive-maintenance/${id}`,
    DELETE: (id: string) => `${API_BASE}/preventive-maintenance/${id}`,
    SKIP: (planId: string) => `${API_BASE}/preventive-maintenance/${planId}/skip`,
    CALENDAR: `${API_BASE}/preventive-maintenance/calendar`,
    COMPLIANCE: `${API_BASE}/preventive-maintenance/compliance`,
  },
  SERVICE_REQUESTS: {
    LIST: `${API_BASE}/service-requests`,
    CREATE: `${API_BASE}/service-requests`,
    DETAIL: (id: string) => `${API_BASE}/service-requests/${id}`,
    UPDATE: (id: string) => `${API_BASE}/service-requests/${id}`,
    RATE: (id: string) => `${API_BASE}/service-requests/${id}/rate`,
    APPROVE: (id: string) => `${API_BASE}/service-requests/${id}/approve`,
    REJECT: (id: string) => `${API_BASE}/service-requests/${id}/reject`,
    ATTACHMENTS: (id: string) => `${API_BASE}/service-requests/${id}/attachments`,
  },
  NOTIFICATIONS: {
    LIST: `${API_BASE}/notifications`,
    MARK_ALL_READ: `${API_BASE}/notifications/mark-all-read`,
    DELETE: (id: string) => `${API_BASE}/notifications/${id}`,
    PREFERENCES: `${API_BASE}/notifications/preferences`,
    ESCALATION_RULES: `${API_BASE}/notifications/escalation-rules`,
  },
  REPORTS: {
    WORK_ORDERS: `${API_BASE}/reports/work-orders`,
    PM_COMPLIANCE: `${API_BASE}/reports/pm-compliance`,
    VENDOR_PERFORMANCE: `${API_BASE}/reports/vendor-performance`,
    ASSET_HISTORY: `${API_BASE}/reports/asset-history`,
    COMPLIANCE: `${API_BASE}/reports/compliance`,
    TECHNICIAN: `${API_BASE}/reports/technician`,
    EXPORT: `${API_BASE}/reports/export`,
  },
  SETTINGS: {
    ORGANIZATION: `${API_BASE}/settings/organization`,
    USER_ME: `${API_BASE}/settings/me`,
    VENDOR: `${API_BASE}/settings/vendor`,
    USER: (id: string) => `${API_BASE}/settings/users/${id}`,
    INVITE_USER: `${API_BASE}/settings/users/invite`,
  },
  INVITATIONS: {
    CREATE: `${API_BASE}/invitations`,
    LIST: `${API_BASE}/invitations`,
    DETAIL: (id: string) => `${API_BASE}/invitations/${id}`,
    RESEND: (id: string) => `${API_BASE}/invitations/${id}/resend`,
    REVOKE: (id: string) => `${API_BASE}/invitations/${id}/revoke`,
  },
  USERS: `${API_BASE}/users`,
};
